global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: 'springboot-app'
#     metrics_path: "/actuator/prometheus"
#     static_configs:
#       - targets: ['springboot-app:8080']
#         labels:
#           group: 'springboot'

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          group: 'springboot'